version: '3.9'
services:
  server:
    build: .
    ports:
      - "80:8081"
    depends_on:
      - db
    networks:
      - some-net
  db:
    build: ./db/
    ports:
      - "1433:1433"
    networks:
      - some-net
networks:
  some-net:
    driver: bridge